// apps/angular-app/src/app/components/navbar/navbar.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';

@Component({
  selector: 'app-navbar',
  standalone: true,
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.css'],
  imports: [CommonModule, RouterModule] // Import RouterModule for routerLink to work
})
export class NavbarComponent {
  isMenuOpen = false;

  toggleMenu(): void {
    this.isMenuOpen = !this.isMenuOpen;
  }

  redirect(path: string, delay: number): void {
    this.toggleMenu();
    setTimeout(() => {
      window.location.href = path;
    }, delay);
  }
}
<nav class="navbar top-0 md:sticky left-0 w-full bg-blue-100 text-base-content shadow-md md:bg-slate-50">
    <div class="w-full max-w-7xl mx-auto px-4 flex items-center justify-between py-3">
      <!-- Logo -->
      <a routerLink="/home" class="text-2xl font-bold text-pink-700 dark:text-pink-500 flex items-center gap-2">
        <img class="w-6 h-6 rounded-lg" src="assets/logo.jpg" alt="Young Eagles Logo" />
        Young Eagles
      </a>
  
      <!-- Desktop Nav -->
      <ul class="flex gap-x-4 hidden md:flex">
        <li><a routerLink="/home" class="hover:text-white hover:bg-pink-500 transition-colors duration-700 px-2 py-1 rounded-lg">Home</a></li>
        <li><a routerLink="/programs" class="hover:text-white hover:bg-pink-500 transition-colors duration-700 px-2 py-1 rounded-lg">Programs</a></li>
        <li
          (click)="redirect('/projects', 2000)"
          class="hover:text-white hover:bg-pink-500 transition-colors duration-700 px-2 py-1 rounded-lg cursor-pointer"
        >
          Projects
        </li>
        <li
          (click)="redirect('/parent', 2000)"
          class="hover:text-white hover:bg-pink-500 transition-colors duration-700 px-2 py-1 rounded-lg cursor-pointer"
        >
          Dashboard
        </li>
        <li><a routerLink="/popupload" class="hover:text-white hover:bg-pink-500 transition-colors duration-700 px-2 py-1 rounded-lg bg-pink-500">Upload POP</a></li>
      </ul>
  
      <!-- Mobile Toggle -->
      <div class="cursor-pointer md:hidden" aria-label="Toggle Menu">
        <span *ngIf="isMenuOpen; else hamburger" (click)="toggleMenu()">✖️</span>
        <ng-template #hamburger>
          <span (click)="toggleMenu()">☰</span>
        </ng-template>
      </div>
    </div>
  
    <!-- Mobile Nav -->
    <ul *ngIf="isMenuOpen" class="md:hidden flex flex-col gap-y-6 text-center pb-4">
      <li><a routerLink="/home" class="hover:text-white hover:bg-pink-500 transition-colors duration-700 px-2 py-1 rounded-lg block" (click)="toggleMenu()">Home</a></li>
      <li><a routerLink="/projects" class="hover:text-white hover:bg-pink-500 transition-colors duration-700 px-2 py-1 rounded-lg block" (click)="toggleMenu()">Projects</a></li>
      <li
        (click)="redirect('/programs', 2000)"
        class="hover:text-white hover:bg-pink-500 transition-colors duration-700 px-2 py-1 rounded-lg block cursor-pointer"
      >
        Programs
      </li>
      <li><a routerLink="/admission" class="hover:text-white hover:bg-pink-500 transition-colors duration-700 px-2 py-1 rounded-lg block" (click)="toggleMenu()">Admission</a></li>
      <li><a routerLink="/contact" class="hover:text-white hover:bg-pink-500 transition-colors duration-700 px-2 py-1 rounded-lg block" (click)="toggleMenu()">Contact</a></li>
      <li
        (click)="redirect('/parent', 2000)"
        class="hover:text-white hover:bg-pink-500 transition-colors duration-700 px-2 py-1 rounded-lg block cursor-pointer"
      >
        Dashboard
      </li>
      <li><a routerLink="/popupload" class="hover:text-white hover:bg-pink-500 transition-colors duration-700 px-2 py-1 rounded-lg block bg-pink-500" (click)="toggleMenu()">Upload POP</a></li>
    </ul>
</nav>

// apps/react-app/src/components/Navbar.jsx
import React, { useState } from "react";
import { Link } from "react-router-dom";
import { GiHamburgerMenu } from "react-icons/gi";
import { RiCloseCircleFill } from "react-icons/ri";
import logo from "../assets/logo.jpg";
import useRedirect from "../hooks/useRedirect";

const styles = {
  link: "hover:text-white hover:bg-pink-500 transition-colors duration-700 px-2 py-1 rounded-lg",
};

function Navbar() {
  const [IsMenuOpen, setIsMenuOpen] = useState(false);
  const redirect = useRedirect();

  const toggleMenu = () => setIsMenuOpen(!IsMenuOpen);
  const handleRedirect = (path) => redirect(path, 2000);

  return (
    <nav className="navbar top-0 md:sticky left-0 w-full bg-gray-100 text-base-content shadow-md md:bg-slate-50">
      <div className="w-full max-w-7xl mx-auto px-4 flex items-center justify-between py-3">
        <Link to="/home" className="text-2xl font-bold text-pink-700 dark:text-pink-500 flex items-center gap-2">
          <img src={logo} alt="Young Eagles Logo" className="h-12 w-12 rounded-full" />
          Young Eagles
        </Link>
        {/* Desktop Nav */}
        <ul className="flex gap-x-4 hidden md:flex">
          <li><Link to="/home" className={styles.link}>Home</Link></li>
          {/* <li><Link to="/about" className={styles.link}>About</Link></li> */}
          <li><Link to="/programs" className={styles.link}>Programs</Link></li>
          {/* <li><Link to="/contact" className={styles.link}>Contact</Link></li> */}

          <li
            onClick={() => {
              toggleMenu();
              setTimeout(() => {
                window.location.href = "/projects";
              }, 2000);
            }}
            className={`${styles.link} cursor-pointer`}
          >
            Projects
          </li>

          <li
            onClick={() => redirect("/parent", 2000)}
            className={`${styles.link} cursor-pointer`}
          >
            Dashboard
          </li>
          <li><Link to="/popupload" className={`${styles.link} bg-pink-500`}>Upload POP</Link></li>
        </ul>
        <div className="cursor-pointer md:hidden" aria-label="Toggle Menu">
          {IsMenuOpen ? (
            <RiCloseCircleFill className="h-6 w-6" onClick={toggleMenu} />
          ) : (
            <GiHamburgerMenu className="h-6 w-6" onClick={toggleMenu} />
          )}
        </div>
      </div>
      {/* Mobile Nav */}
      {IsMenuOpen && (
        <ul className="md:hidden flex flex-col gap-y-6 text-center pb-4">
          <li><Link to="/home" className={`${styles.link} block`} onClick={toggleMenu}>Home</Link></li>
          <li><Link to="/programs" className={`${styles.link} block`} onClick={toggleMenu}>Programs</Link></li>
          <li
            onClick={() => {
              toggleMenu();
              setTimeout(() => {
                window.location.href = "/projects"; // or full Angular app URL
              }, 2000); // 2000ms = 2 seconds
            }}
            className={`${styles.link} block`}
          >
            Projects
          </li>          
          {/* <li><Link to="/admission" className={`${styles.link} block`} onClick={toggleMenu}>Admission</Link></li> */}
          {/* <li><Link to="/contact" className={`${styles.link} block`} onClick={toggleMenu}>Contact</Link></li> */}
          <li
            onClick={() => redirect("/parent", 2000)}
            className={`styles.link} cursor-pointer`}
          >
            Dashboard
          </li>
          <li><Link to="/popupload" className={`${styles.link} block bg-pink-500`} onClick={toggleMenu}>Upload POP</Link></li>
        </ul>
      )}
    </nav>
  );
}

export default Navbar;
